# Generated by Django 3.0.8 on 2020-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_km', models.DecimalField(decimal_places=2, max_digits=9)),
                ('litter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_litter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('trip_memo', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
