# Generated by Django 3.0.8 on 2020-07-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0003_auto_20200716_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='average_mileage',
        ),
        migrations.RemoveField(
            model_name='log',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='log',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='log',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='log',
            name='total_km',
        ),
        migrations.RemoveField(
            model_name='log',
            name='total_litter',
        ),
    ]
