# Generated by Django 3.0.8 on 2020-07-19 04:38

import DiaryApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0004_auto_20200718_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[DiaryApp.models.check_km]),
        ),
        migrations.AlterField(
            model_name='log',
            name='litter',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[DiaryApp.models.check_litter]),
        ),
        migrations.AlterField(
            model_name='log',
            name='price',
            field=models.IntegerField(validators=[DiaryApp.models.check_price]),
        ),
        migrations.AlterField(
            model_name='log',
            name='trip_memo',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, '100文字以内にしてください。')]),
        ),
    ]
